language: node_js
node_js:
  - "4.5"
master:
  script:
    - npm install -g bower firebase-tools polymer-cli
    - bower install
    - polymer build
  after_success:
    - firebase deploy --token $FIREBASE_TOKEN
